# Generated by Django 6.0.7 on 2026-08-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('primeiro_nome', models.CharField(max_length=150)),
                ('ultimo_nome', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('ativo', models.BooleanField()),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['username'],
                'managed': False,
            },
        ),
    ]
